### ISSUE TITLE
Docker image got bigger after switching to using ADD

### ISSUE THREAD

**Issue by maniator** [maniator/dind-buildx#3]
**Describe the bug**
After switching to using a docker `ADD` in this PR #1 the size of the docker image increased by ~25mb

**To Reproduce**
Build the docker container locally before and after the change

**Expected behavior**
Expect that both are around the same size

**Screenshots**

![image](https://user-images.githubusercontent.com/539579/127345898-f7e93f6a-50d4-444d-b0e4-fa63232b6251.png)

Can we investigate why that happened?

**Comment by maniator** [comment]
@joakimr-axis -- I am going to look into this (unless you'd like to?)

**Comment by maniator** [comment]
As per the docs here: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy

I will be reverting #1 and updating again to use wget instead (updating also with a multistage build)

![image](https://user-images.githubusercontent.com/539579/127355793-287e3834-cfd7-4f0f-8361-d79a2441cc2a.png)

**Comment by joakimr-axis** [comment]
> 
> I will be reverting #1 and updating again to use wget instead

`wget` here is problematic, since running `docker build` for dind-buildx behind a corporate proxy (not every corporate proxy, but at least one) fails with

`wget: server returned error: HTTP/1.1 501 Not Implemented`

Using `curl` instead mitigates that but adds an install step for curl

`RUN apk add -U curl
RUN mkdir -p ~/.docker && echo '{"experimental": "enabled"}' > ~/.docker/config.json \
    && mkdir -p $HOME/.docker/cli-plugins/ && curl -L -o $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL \
    && chmod a+x $HOME/.docker/cli-plugins/docker-buildx`
    
When it comes to image size: the downloaded docker-buildx binaries are not stripped.

```shell
$ file buildx-v0.5.1.linux-amd64 buildx-v0.6.0.linux-amd64 
buildx-v0.5.1.linux-amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=R42x1RrGJUle99LLyWPY/6XkhxhdDS4swyz4MGXcE/461hXXnCgz1Qs53EKtag/QaEW1mwB8tlksaTIIOqh, not stripped
buildx-v0.6.0.linux-amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=fLqH0A1F3fz3tutlwRN4/se6yjjlE44dgdh6K0L_R/hqL2oeVePdFmhAp2152J/aXiJjaGQUJUT_dntC2BP, not stripped
```

So perhaps it might be an idea to strip the binary in order to shave some MBs from the image size.

```shell
$ du -m buildx-v0.5.1.linux-amd64 buildx-v0.6.0.linux-amd64 
59	buildx-v0.5.1.linux-amd64
59	buildx-v0.6.0.linux-amd64
$ strip buildx-v0.5.1.linux-amd64 buildx-v0.6.0.linux-amd64
$ du -m buildx-v0.5.1.linux-amd64 buildx-v0.6.0.linux-amd64 
44	buildx-v0.5.1.linux-amd64
43	buildx-v0.6.0.linux-amd64
```

**Comment by joakimr-axis** [comment]
A suggestion on how to mitigate the wget/curl/proxy issue, doing the binary strip, using multistage to despite that not have more than the docker-buildx binary added in the output image and having global ARGs for those stages (with the added bonus that those can be overridden with arguments to docker build for e.g. testing newer versions) is to be found here: https://github.com/maniator/dind-buildx/pull/5
