### ISSUE TITLE
snyk setup for CI seems broken

### ISSUE THREAD

**Issue by joakimr-axis** [maniator/dind-buildx#6]
**Describe the bug**
Snyk steps in CI pipeline fail with:

_`snyk` requires an authenticated account. Please run `snyk auth` and try again._

and

_Error: Path does not exist: snyk.sarif_

**To Reproduce**

Create a PR, see CI pipeline output

**Expected behavior**

Failure should be only caused by the PR content itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/47358365/127449035-6e3629e5-9abd-4208-95b2-3bdeee699d61.png)

**Comment by maniator** [comment]
Hmmm I will look into this

**Comment by maniator** [comment]
I believe I fixed it @joakimr-axis 

Rebase PR #5 and I think it should work now.

I messed up setting env secrets in the github settings

**Comment by maniator** [comment]
> I believe I fixed it @joakimr-axis
> 
> Rebase PR #5 and I think it should work now.
> 
> I messed up setting env secrets in the github settings

I will do this for you, I just want to add one commit to clean up some code (hopefully that is ok) and you can review.

**Comment by maniator** [comment]
Hmmm this is still happening

![image](https://user-images.githubusercontent.com/539579/127543058-c30e22ef-47b0-4d7d-9535-21e1d6d80771.png)


I will look into it more -- in the meantime can you look @ the commit I added?

**Comment by maniator** [comment]
I updated the snyk action as per https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/ with `pull_request_target` instead of `pull_request` and pulled the same change into your PR (can rebase your PR off of main to prune those extra commit)

**Comment by joakimr-axis** [comment]
I definitely seems to work now from what I can see, thanks!
